language: cpp
sudo: required
virtualenv:
  system_site_packages: true
python:
    - "2.7"
    - "3.5"
git:
    submodules: false
matrix:
  include:
    - os: osx
      osx_image: xcode7.3 # OS X 10.11.1
      compiler: clang
      before_install:
        - git submodule update --init
        - sw_vers -productVersion
        - brew update
        - brew outdated cmake || brew upgrade cmake
        - brew unlink python
        - brew install python tbb
      install:
        - pip3 install -r python/requirements.txt
        - git submodule update --init
        - mkdir third_party/build
        - cd third_party/build
        - cmake ..
        - make -j 4
        - make install
        - cd ../..
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make -j 4
        - cd ..
        - ./setup.py install
      after_success:
        - export PYMESH_PATH=`pwd`
        - cd build
        - make tests
        - cd ..
        - python -c "import pymesh; pymesh.test()"
    - os: linux
      dist: xenial
      python: "2.7"
      addons:
        apt:
          update: true
          packages:
            - libeigen3-dev
            - libgmp-dev
            - libgmpxx4ldbl
            - libmpfr-dev
            - libboost-dev
            - libboost-thread-dev
            - libtbb-dev
            - python3-dev
      install:
        # Conda (Miniconda)
        - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        # Useful for debugging any issues with conda
        - conda info -a
        # Create conda enviroment
        - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
        - source activate test-environment
        - conda install cmake
        - git submodule update --init
        - pip install -r python/requirements.txt
        - mkdir third_party/build
        - cd third_party/build
        - cmake ..
        - make -j 4
        - make install
        - cd ../..
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make -j 4
        - cd ..
        - ./setup.py install
      after_success:
        - export PYMESH_PATH=`pwd`
        - cd build
        - make tests
        - cd ..
        - python -c "import pymesh; pymesh.test()"
