version: 2
jobs:
    "py3.6":
        machine: true
        steps:
            - checkout
            - run:
                command: |
                    docker login -u $DOCKER_USER -p $DOCKER_PASS
                    docker build -t pymesh/pymesh:py3.6 docker/py3.6
                    [ "$CIRCLE_BRANCH" = "master" ] && docker push pymesh/pymesh:py3.6
                no_output_timeout: 1200
    "py3.6-slim":
        machine: true
        steps:
            - checkout
            - run: |
                cd docker/py3.6-slim
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                ./build.sh
                docker push pymesh/pymesh:py3.6-slim
                docker tag pymesh/pymesh:py3.6-slim pymesh/pymesh
                docker push pymesh/pymesh
    "py2.7":
        machine: true
        steps:
            - checkout
            - run:
                command: |
                    docker login -u $DOCKER_USER -p $DOCKER_PASS
                    docker build -t pymesh/pymesh:py2.7 docker/py2.7
                    [ "$CIRCLE_BRANCH" = "master" ] && docker push pymesh/pymesh:py2.7
                no_output_timeout: 1200
    "py2.7-slim":
        machine: true
        steps:
            - checkout
            - run: |
                cd docker/py2.7-slim
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                ./build.sh
                docker push pymesh/pymesh:py2.7-slim

workflows:
    version: 2
    build_and_test_and_deploy:
        jobs:
            - "py3.6"
            - "py2.7"
            - "py3.6-slim":
                requires:
                    - "py3.6"
                filters:
                    branches:
                        only: master
            - "py2.7-slim":
                requires:
                    - "py2.7"
                filters:
                    branches:
                        only: master

